### ISSUE TITLE
fails to load jactivity.js

### ISSUE THREAD

**Issue by riedel** [teco-kit/jActivity#4] opened 2016-11-05 09:03 UTC
`GET http://192.168.99.100/api/classifier/123/jactivity.js`

returns 502

```
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /api/classifier/123/jactivity.js.

Reason: Error reading from remote server
```

running on the demo server

`GET http://jactivity.teco.edu/api/classifier/123/jactivity.js`

returns 503

```
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.
```

**Comment by davidgreiner** [comment] 2016-11-06 22:10
Problem was caused by crashed NodeJS Server due to "Headers can not be set after being send". Should be fixed with 6d662b8d49cd8d87fa18075c49979db94ccf557c. Server has been stress tested with 25 simultaneous connections.

**Closed as completed by davidgreiner** 2016-11-06 22:10 UTC
